name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (all branches)
        uses: actions/checkout@v2
          - run: |
              git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      - name: Clean-install dependencies
        run: npm ci

      - name: Production-Build
        uses: docker://trion/ng-cli:latest
        with:
          args: /bin/sh -c "npm run build:element; npm run build:page -- --base-href=${GITHUB_REPOSITORY#*/}; rm -rf node_modules; chmod -f -R a+rwx dist; true"

      - name: Deployment auf GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@example.com"
          git checkout gh-pages
          ls | grep -v dist | xargs rm -r
          find dist -mindepth 2 -exec mv {} . \;
          rm -rf dist
          git add .
          git commit -m "updated GitHub Pages"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push --force-with-lease origin gh-pages
